name: Fetch

on:
  push:
    branches: [ teller_import_integration ]
  
  pull_request:
    branches: [ teller_import_integration ]

  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    env:
      MINTABLE_CONFIG: ${{ secrets.MINTABLE_CONFIG }}

    steps:
    - uses: actions/checkout@v2

    # Decode TELLER_CERTIFICATE secret and write to teller_certificate.pem
    - name: Decode TELLER_CERTIFICATE and save as .pem
      run: |
        echo "${{ secrets.TELLER_CERTIFICATE }}" | base64 -d > teller_certificate.pem

    # Decode TELLER_PRIVATE_KEY secret and write to teller_private_key.pem
    - name: Decode TELLER_PRIVATE_KEY and save as .pem
      run: |
        echo "${{ secrets.TELLER_PRIVATE_KEY }}" | base64 -d > teller_private_key.pem

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm run build
    - run: node ./lib/scripts/cli.js fetch --ci
